version: '3'
services:
  db:
    container_name: rudder-db
    env_file:
      - db.env
    image: mongo:4.2.8
    networks:
      - rudder

  nginx:
    container_name: nginx
    depends_on:
      - api
    image: nginx:1.17-alpine
    networks:
      - rudder
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build: .
    container_name: rudder-api
    env_file:
      - api.env
    image: tjlaekem/rudder-api:latest
    links:
      - db
    networks:
      - rudder
    volumes:
      - .:/app

networks:
  rudder:
